/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf310.gestionarcontactos;
import inf310.arbolesbiinariosbusqueda.ArbolBinarioBusqueda;
import inf310.arbolesbiinariosbusqueda.AVL;
import MVias.ArbolMViasBusqueda;
import java.awt.List;
import java.awt.TextField;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import inf310.gestionarcontactos.Contacto;

/**
 *
 * @author Charles
 */
public class Contactos extends javax.swing.JFrame {
    private ArbolBinarioBusqueda<Contacto> ArbolBinarioBusqueda;
    private AVL<Contacto> AVL;
    private ArbolMViasBusqueda<Contacto> ArbolMviasBusqueda;

    /**
     * Creates new form Contactos
     */
    public Contactos() {
        initComponents();
        ArbolBinarioBusqueda = new ArbolBinarioBusqueda<>();
        AVL = new AVL<>();
        ArbolMviasBusqueda = new ArbolMViasBusqueda<>();
    }
    
    public void agregarContacto(Contacto contacto) {
        ArbolBinarioBusqueda.insertar(contacto);  // O en el árbol que prefieras
        AVL.insertar(contacto);
        ArbolMviasBusqueda.insertar(contacto);
    }
    
    public Contacto buscarContacto(String nombre){
        // Mostrar ventana de selección de árbol
        String[] opciones = {"Arbol Binario", "AVL", "MVias"};
        String seleccion = (String) JOptionPane.showInputDialog(
            null, 
            "Seleccione el árbol que desea usar para buscar:",
            "Seleccionar Árbol",
            JOptionPane.QUESTION_MESSAGE, 
            null, 
            opciones, 
            opciones[0]
        );

        Contacto dummy = new Contacto(nombre, "");
        
        // Verifica la selección y realiza la búsqueda en el árbol correspondiente
        if ("Arbol Binario".equals(seleccion)) {
            return ArbolBinarioBusqueda.buscar(dummy);
        } else if ("AVL".equals(seleccion)) {
            return AVL.buscar(dummy);
        } else if ("MVias".equals(seleccion)) {
            return ArbolMviasBusqueda.buscar(dummy);
        } else {
            JOptionPane.showMessageDialog(null, "No se seleccionó un árbol válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    // Método para eliminar un contacto usando un árbol seleccionado
    public void eliminarContacto(String nombre) {
        // Mostrar ventana de selección de árbol
        String[] opciones = {"Arbol Binario", "AVL", "MVias"};
        String seleccion = (String) JOptionPane.showInputDialog(
            null, 
            "Seleccione el árbol que desea usar para eliminar:",
            "Seleccionar Árbol",
            JOptionPane.QUESTION_MESSAGE, 
            null, 
            opciones, 
            opciones[0]
        );

        Contacto dummy = new Contacto(nombre, "");
        
        // Verifica la selección y realiza la eliminación en el árbol correspondiente
        if ("Arbol Binario".equals(seleccion)) {
            ArbolBinarioBusqueda.eliminar(dummy);
            JOptionPane.showMessageDialog(null, "Contacto eliminado en Árbol Binario");
        } else if ("AVL".equals(seleccion)) {
            AVL.eliminar(dummy);
            JOptionPane.showMessageDialog(null, "Contacto eliminado en AVL");
        } else if ("MVias".equals(seleccion)) {
            ArbolMviasBusqueda.eliminar(dummy);
            JOptionPane.showMessageDialog(null, "Contacto eliminado en MVias");
        } else {
            JOptionPane.showMessageDialog(null, "No se seleccionó un árbol válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestionar Contactos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 230, 70);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Celular");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 140, 160, 20);

        jTextField1.setName(""); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 90, 130, 40);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 80, 72, 23);

        jButton2.setText("Eliminar");
        jButton2.setName(""); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 160, 73, 23);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(310, 120, 72, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 310, 220);

        jButton4.setText("PreOrden");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(330, 230, 80, 23);

        jButton5.setText("InOrden");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(330, 260, 80, 23);

        jButton6.setText("PosOrden");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(330, 290, 82, 23);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(10, 170, 260, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 160, 20);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nombre = jTextField1.getText();
        eliminarContacto(nombre);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String nombre = jTextField1.getText();
        Contacto resultado = buscarContacto(nombre);
        
        if (resultado != null) {
            JOptionPane.showMessageDialog(null, "Contacto encontrado: " + jTextField1.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Contacto no encontrado.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Obtener los valores introducidos en los TextFields
        String nombre = jTextField1.getText();
        String celular = jTextField2.getText();
    
        // Crear un nuevo objeto Contacto
        Contacto nuevoContacto = new Contacto(nombre, celular);

        // Insertar en todos los árboles
        ArbolBinarioBusqueda.insertar(nuevoContacto); // Guarda en Arbol Binario
        AVL.insertar(nuevoContacto);      // Guarda en AVL
         ArbolMviasBusqueda.insertar(nuevoContacto);    // Guarda en MVias

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(null, "Contacto guardado en todos los árboles.");
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void mostrarRecorrido(String tipoRecorrido) {
        String[] opciones = {"Arbol Binario", "AVL", "MVias"};
        String seleccion = (String) JOptionPane.showInputDialog(
            null,
            "Seleccione el árbol para realizar el recorrido " + tipoRecorrido + ":",
            "Seleccionar Árbol",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if (seleccion == null) {
            return; // Si no selecciona nada, no hacer nada
        }

        List<Contacto> recorrido = new ArrayList<>();
        switch (seleccion) {
            case "Arbol Binario" -> {
                if ("PreOrden".equals(tipoRecorrido)) {
                    recorrido = ArbolBinarioBusqueda.recorridoEnPreOrden();
                } else if ("InOrden".equals(tipoRecorrido)) {
                    recorrido = ArbolBinarioBusqueda.recorridoEnInOrden();
                } else if ("PostOrden".equals(tipoRecorrido)) {
                    recorrido = ArbolBinarioBusqueda.recorridoEnPostOrden();
                }
            }
            case "AVL" -> {
                if ("PreOrden".equals(tipoRecorrido)) {
                    recorrido = AVL.recorridoEnPreOrden();
                } else if ("InOrden".equals(tipoRecorrido)) {
                    recorrido = AVL.recorridoEnInOrden();
                } else if ("PostOrden".equals(tipoRecorrido)) {
                    recorrido = AVL.recorridoEnPostOrden();
                }
            }
            case "MVias" -> {
                if ("PreOrden".equals(tipoRecorrido)) {
                    recorrido = ArbolMviasBusqueda.recorridoEnPreOrden();
                } else if ("InOrden".equals(tipoRecorrido)) {
                    recorrido = ArbolMviasBusqueda.recorridoEnInOrden();
                } else if ("PostOrden".equals(tipoRecorrido)) {
                    recorrido = ArbolMviasBusqueda.recorridoEnPostOrden();
                }
            }
            default -> {
                JOptionPane.showMessageDialog(null, "Árbol no válido.");
                return;
            }
        }
        // Mostrar el resultado del recorrido en jTextArea1
        StringBuilder resultado = new StringBuilder("Recorrido " + tipoRecorrido + ":\n");
        for (Contacto contacto : recorrido) {
            resultado.append(contacto.getNombre()).append(" - ").append(contacto.getTelefono()).append("\n");
        }
        jTextArea1.setText(resultado.toString());
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mostrarRecorrido("PreOrden");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mostrarRecorrido("InOrden");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        mostrarRecorrido("PostOrden");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
